name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@master

    - name: Install dependencies
      run: |
        Rscript -e "if (!require('rvest')) install.packages('rvest')"
        Rscript -e "if (!require('xml2')) install.packages('xml2')"

    - name: Fetch stats and update README.md
      run: |
        Rscript scrape-profile-stats.R

    - name: Commit and push if needed
      run: |-
        git diff
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git add -A
        git commit -m "Updated README.md automatically" || exit 0
        git push
